import "./globals.css";
import localFont from 'next/font/local'
import StoreProvider from "@/components/features/StoreProvider";
import { Suspense } from "react";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const iranSansFont=localFont(
  {src:'../../public/fonts/iransansx/IRANSansXRegular.ttf'},
  {src:'../../public/fonts/iransansx/IRANSansXBlack.ttf'},
  {src:'../../public/fonts/iransansx/IRANSansXBold.ttf'},
  {src:'../../public/fonts/iransansx/IRANSansXDemiBold.ttf'},
  {src:'../../public/fonts/iransansx/IRANSansXLight.ttf'},
  {src:'../../public/fonts/iransansx/IRANSansXMedium.ttf'},
  {src:'../../public/fonts/iransansx/IRANSansXThin.ttf'},
  {src:'../../public/fonts/iransansx/IRANSansXUltraLight.ttf'})


export default function RootLayout({children}) {

  return (
    <html lang="fa">
      <body  className={iranSansFont.className }>
      <StoreProvider>
        
          <>{children}</>
        
      </StoreProvider> 
      </body>
    </html>
  );
}
